<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.4.551">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Automating Metagenomics Analyses with Bash Scripts - Diversity Tackled With R</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<link href="../../docs/lesson06-taxonomic-annotations/03-hands_on-diversity.html" rel="next">
<link href="../../docs/lesson06-taxonomic-annotations/01-taxonomic.html" rel="prev">
<script src="../../site_libs/quarto-html/quarto.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  </head><body class="nav-sidebar docked nav-fixed">yes

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../../styles.css">




<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a href="../../index.html" class="navbar-brand navbar-brand-logo">
    <img src="../../images/cloud-span-icon.png" alt="Cloud-SPAN logo." class="navbar-logo">
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-lessons" role="button" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Lessons</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-lessons">    
        <li>
    <a class="dropdown-item" href="../../index.html">
 <span class="dropdown-text">Course Overview</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../docs/lesson01-files-and-directories/index.html">
 <span class="dropdown-text">Files and Directories</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../docs/lesson02-using-the-command-line/index.html">
 <span class="dropdown-text">Using the Command Line</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../docs/lesson03-qc-assembly/index.html">
 <span class="dropdown-text">QC &amp; Assembly</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../docs/lesson04-polishing/index.html">
 <span class="dropdown-text">Polishing</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../docs/lesson05-binning-functional-annotation/index.html">
 <span class="dropdown-text">Binning and Functional Annotation</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../docs/lesson06-taxonomic-annotations/index.html">
 <span class="dropdown-text">Taxonomic Annotations</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../docs/lesson07-automation-bash-scripts/index.html">
 <span class="dropdown-text">Automating Analyses with Bash Scripts</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="../../docs/miscellanea/setup.html"> 
<span class="menu-text">Setup</span></a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-extras" role="button" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Extras</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-extras">    
        <li>
    <a class="dropdown-item" href="../../docs/miscellanea/reference.qmd">
 <span class="dropdown-text">Reference</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../docs/miscellanea/about.html">
 <span class="dropdown-text">About</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../docs/miscellanea/data.qmd">
 <span class="dropdown-text">Data</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../docs/miscellanea/faq.qmd">
 <span class="dropdown-text">Frequently Asked Questions</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../docs/miscellanea/instructornotes.qmd">
 <span class="dropdown-text">Instructor Notes</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="../../docs/miscellanea/license.html"> 
<span class="menu-text">License</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../docs/miscellanea/codeofconduct.html"> 
<span class="menu-text">Code of Conduct</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
          <div class="quarto-navbar-tools">
  <a href="" class="quarto-reader-toggle quarto-navigation-tool px-1" onclick="window.quartoToggleReader(); return false;" title="Toggle reader mode">
  <div class="quarto-reader-toggle-btn">
  <i class="bi"></i>
  </div>
</a>
</div>
      </div> <!-- /container-fluid -->
    </nav>
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../../docs/lesson06-taxonomic-annotations/index.html">Taxonomic Annotations</a></li><li class="breadcrumb-item"><a href="../../docs/lesson06-taxonomic-annotations/02-Diversity-tackled-with-R.html">Diversity Tackled With R</a></li></ol></nav>
        <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../docs/lesson01-files-and-directories/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Files and Directories</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../docs/lesson01-files-and-directories/01-understanding-file-systems.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Understanding your file system</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../docs/lesson01-files-and-directories/02-logging-onto-cloud.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Logging onto the Cloud</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../docs/lesson01-files-and-directories/03-shell-introduction.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Introducing the Shell</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../docs/lesson02-using-the-command-line/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Using the Command Line</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../docs/lesson02-using-the-command-line/01-navigating-file-directories.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Navigating Files and Directories</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../docs/lesson02-using-the-command-line/02-working-with-file.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Working with Files and Directories</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../docs/lesson02-using-the-command-line/03-redirection.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Redirection</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../docs/lesson03-qc-assembly/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">QC &amp; Assembly</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../docs/lesson03-qc-assembly/00-introduction-meta.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Introduction to Metagenomics</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../docs/lesson03-qc-assembly/01-QC-quality-raw-reads.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Assessing Read Quality, Trimming and Filtering</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../docs/lesson03-qc-assembly/02-assembly.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Metagenome Assembly</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../docs/lesson04-polishing/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Polishing</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../docs/lesson04-polishing/01-polishing-assembly.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Polishing an assembly</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../docs/lesson04-polishing/02-QC-polished-assembly.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">QC polished assembly</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../docs/lesson05-binning-functional-annotation/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Binning &amp; Functional Annotation</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../docs/lesson05-binning-functional-annotation/01-binning.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Metagenome Binning</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../docs/lesson05-binning-functional-annotation/02-binning_quality.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">QC of metagenome bins</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../docs/lesson05-binning-functional-annotation/03-Functional-annotation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Functional annotation</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../docs/lesson06-taxonomic-annotations/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Taxonomic Annotations</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../docs/lesson06-taxonomic-annotations/01-taxonomic.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Taxonomic Assignment</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../docs/lesson06-taxonomic-annotations/02-Diversity-tackled-with-R.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text">Diversity Tackled With R</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../docs/lesson06-taxonomic-annotations/03-hands_on-diversity.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Taxonomic Analysis with R</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../docs/lesson07-automation-bash-scripts/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Automating Analyses with Bash Scripts</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-7" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../docs/lesson07-automation-bash-scripts/01-scripting-intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Introduction to Bash Scripting</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../docs/lesson07-automation-bash-scripts/02-base-automation-script.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Base Automation Script</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#what-is-diversity" id="toc-what-is-diversity" class="nav-link active" data-scroll-target="#what-is-diversity">What is diversity?</a>
  <ul class="collapse">
  <li><a href="#alpha-α-diversity" id="toc-alpha-α-diversity" class="nav-link" data-scroll-target="#alpha-α-diversity">Alpha (α) diversity</a></li>
  <li><a href="#beta-β-diversity" id="toc-beta-β-diversity" class="nav-link" data-scroll-target="#beta-β-diversity">Beta (β) diversity</a></li>
  </ul></li>
  <li><a href="#how-do-we-calculate-diversity-from-metagenomic-samples" id="toc-how-do-we-calculate-diversity-from-metagenomic-samples" class="nav-link" data-scroll-target="#how-do-we-calculate-diversity-from-metagenomic-samples">How do we calculate diversity from metagenomic samples?</a></li>
  <li><a href="#what-part-of-the-kraken-output-do-we-need" id="toc-what-part-of-the-kraken-output-do-we-need" class="nav-link" data-scroll-target="#what-part-of-the-kraken-output-do-we-need">What part of the Kraken output do we need?</a></li>
  <li><a href="#create-the-biom-table" id="toc-create-the-biom-table" class="nav-link" data-scroll-target="#create-the-biom-table">Create the BIOM table</a></li>
  <li><a href="#analyse-the-biom-table-using-r" id="toc-analyse-the-biom-table-using-r" class="nav-link" data-scroll-target="#analyse-the-biom-table-using-r">Analyse the BIOM table using R</a>
  <ul class="collapse">
  <li><a href="#option-a-i-know-r-and-rstudio." id="toc-option-a-i-know-r-and-rstudio." class="nav-link" data-scroll-target="#option-a-i-know-r-and-rstudio.">Option A: I know R and RStudio.</a></li>
  <li><a href="#option-b-i-dont-know-r-and-rstudio." id="toc-option-b-i-dont-know-r-and-rstudio." class="nav-link" data-scroll-target="#option-b-i-dont-know-r-and-rstudio.">Option B: I don’t know R and RStudio.</a></li>
  <li><a href="#start-the-analysis" id="toc-start-the-analysis" class="nav-link" data-scroll-target="#start-the-analysis">Start the Analysis</a></li>
  </ul></li>
  <li><a href="#plot-alpha-diversity" id="toc-plot-alpha-diversity" class="nav-link" data-scroll-target="#plot-alpha-diversity">Plot alpha diversity</a></li>
  <li><a href="#beta-diversity" id="toc-beta-diversity" class="nav-link" data-scroll-target="#beta-diversity">Beta diversity</a></li>
  <li><a href="#reading" id="toc-reading" class="nav-link" data-scroll-target="#reading">Reading</a></li>
  </ul>
<div class="toc-actions"><ul><li><a href="https://github.com/Cloud-SPAN/nercMtGn-bashAutomation/edit/main/docs/lesson06-taxonomic-annotations/02-Diversity-tackled-with-R.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li><li><a href="https://github.com/Cloud-SPAN/nercMtGn-bashAutomation/issues/new" class="toc-action"><i class="bi empty"></i>Report an issue</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../../docs/lesson06-taxonomic-annotations/index.html">Taxonomic Annotations</a></li><li class="breadcrumb-item"><a href="../../docs/lesson06-taxonomic-annotations/02-Diversity-tackled-with-R.html">Diversity Tackled With R</a></li></ol></nav>
<div class="quarto-title">
<h1 class="title">Diversity Tackled With R</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p>Once we know the taxonomic composition of our metagenomic sequencing data we can characterise them by their diversity. In this episode we will first define what we mean by diversity and then calculate the α diversity in our sample. We will also calculate the diversity of another sample.</p>
<section id="what-is-diversity" class="level2">
<h2 class="anchored" data-anchor-id="what-is-diversity">What is diversity?</h2>
<p>Species diversity is the number of species in a system and the relative abundance of each of those species. It can be defined on three different scales (Whittaker, 1960).</p>
<ol type="1">
<li>the total species diversity in an ecosystem known as <strong>gamma (γ) diversity</strong></li>
<li>average diversity at a local site, known as <strong>alpha (α) diversity</strong></li>
<li>the difference in diversity between local sites, known as <strong>beta (β) diversity</strong></li>
</ol>
<p>A metagenome can be considered a local site. In this episode we will calculate α diversity (that within a metagenome) and β diversity (that between metagenomes).</p>
<section id="alpha-α-diversity" class="level3">
<h3 class="anchored" data-anchor-id="alpha-α-diversity">Alpha (α) diversity</h3>
<p>The simplest measure of α diversity is the number of species, or species <strong>richness</strong>. However, most indices of α diversity take into account both the number of species and their relative abundances, or species <strong>evenness</strong>. Different diversity indices weight these two components differently.</p>
<table class="table">
<colgroup>
<col style="width: 35%">
<col style="width: 26%">
<col style="width: 24%">
<col style="width: 13%">
</colgroup>
<thead>
<tr class="header">
<th>α Diversity Index</th>
<th>Description</th>
<th>Calculation</th>
<th>Where</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Shannon (H)</td>
<td>Estimation of species richness and species evenness. More weight on richness.</td>
<td><span class="math display">\[H = - \sum_{i=1}^{S} p_{i} \ln{p_{i}}\]</span></td>
<td><span class="math display">\[S\]</span> is the number of OTUs and <span class="math display">\[p_{i}\]</span> is the proportion of the community represented by OTU</td>
</tr>
<tr class="even">
<td>Simpson’s (D)</td>
<td>Estimation of species richness and species evenness. More weight on evenness.</td>
<td><span class="math display">\[D = \frac{1}{\sum_{i=1}^{S} p_{i}^{2}}\]</span></td>
<td><span class="math display">\[S\]</span> is Total number of the species in the community and <span class="math display">\[p_{i}\]</span> is the proportion of community represented by OTU i</td>
</tr>
<tr class="odd">
<td>Chao1</td>
<td>Abundance based on species represented by a single individual (singletons) and two individuals (doubletons).</td>
<td><span class="math display">\[S_{chao1} = S_{Obs} + \frac{F_{1} \times (F_{1} - 1)}{2 \times (F_{2} + 1)}\]</span></td>
<td><span class="math display">\[F_{1}\]</span> and <span class="math display">\[F_{2}\]</span> are the counts of singletons and doubletons respectively and <span class="math display">\[S_{chao1}=S_{Obs}\]</span> is the number of observed species</td>
</tr>
</tbody>
</table>
<p><a href="{{ page.root }}/fig/03-07-01.png"> <img src="{{ page.root }}/fig/03-07-01.png" alt="Diagram to demonstratealpha diversity. Three lakes are shown, A, B and C. In lake A, we have three fishes, each one of a different species. In lake B, we have two fishes each one of a different species.And in lake C we have four fishes, each one of different species."> </a> <em> Figure 1. Alpha diversity represented by fish in a pond. Here, alpha diversity is measured in the simplest way using species richness. </em></p>
</section>
<section id="beta-β-diversity" class="level3">
<h3 class="anchored">Beta (β) diversity</h3>
<p>β diversity measures how different two or more communities are in their richness, evenness or both.</p>
<table class="table">
<colgroup>
<col style="width: 57%">
<col style="width: 42%">
</colgroup>
<thead>
<tr class="header">
<th>β Diversity Index</th>
<th>Description</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Bray–Curtis dissimilarity</td>
<td>The compositional <em>dissimilarity</em> between two metagenomes, based on counts in each metagenome. Ranges from 0 (the two metagenomes have the same species composition) to 1 (the two metagenomes do not share any species). Bray–Curtis dissimilarity emphasises abundance.</td>
</tr>
<tr class="even">
<td>Jaccard distance</td>
<td>Also ranges from 0 (the two metagenomes have the same species) to 1 (the two metagenomes do not share any species) but is based on the presence or absence of species only. This means it emphasises richness.</td>
</tr>
<tr class="odd">
<td>UniFrac</td>
<td>Differs from the Bray-Curtis dissimilarity and Jaccard distance by including the relatedness between taxa in a metagenome. Measures the phylogenetic distance between metagenomes as the proportion of unshared phylogenetic tree branches. Weighted-Unifrac takes into account the relative abundance of taxa shared between samples; unweighted-Unifrac only considers presence or absence.</td>
</tr>
</tbody>
</table>
<p>Figure 2 shows α and the β diversity for three lakes. The most simple way to calculate the β diversity is to calculate the number of species that are unique in two lakes. For example, the number of species in Lake A (the α diversity) is 3 and 1 of these is also found in Lake C; the number of species in Lake C is 2 and 1 of these is also in Lake A. The β diversity between A and C is calculated as (3 - 1) + (2 - 1) = 3</p>
<p><a href="{{ page.root }}/fig/03-07-02.png"> <img src="{{ page.root }}/fig/03-07-02.png" alt="Alpha and Beta diversity diagram: Each lake has a different number of species. The number of species in Lake A (the α diversity) is 3 and 1 of these is also found in Lake C; the number of species in Lake C is 2 and 1 of these is also in Lake A. The β diversity between A and C is calculated as (3 - 1) + (2 - 1) = 3. The number of species in Lake B (the α diversity) is 3 and 2 of these is also found in Lake A; the number of species in Lake A is 3 and 2 of these is also in Lake B. The β diversity between A and B is calculated as (3 - 2) + (3 - 2) = 2"> </a> <em> Figure 2. Alpha and Beta diversity represented by fishes in a pond.<em></em></em></p><em><em>
<blockquote class="blockquote">
<h2 id="exercise-1" class="anchored" data-anchor-id="beta-β-diversity">Exercise 1:</h2>
<p>In the next picture there are two lakes with different fish species: <a href="{{ page.root }}/fig/03-07-01e.png"> <img src="{{ page.root }}/fig/03-07-01e.png" alt="In lake A, we have four different species, two of these species have 3 specimens each one. This lake also have two specimens of another species and only one specimen of the other specie. We got nine fishes total. On the other hand, lake B has only three different species, the most populated species has five specimens and we have only one specimen of the other two species. We got seven species total in lake B "> </a> Which of the options below is true: 1. α diversity of A = 4, α diversity of B = 3, β diversity between A and B = 1 2. α diversity of A = 4, α diversity of B = 3, β diversity between A and B = 5 3. α diversity of A = 9, α diversity of B = 7, β diversity between A and B= 16</p>
<p>Please, paste your result on the collaborative document provided by instructors.</p>
<blockquote class="blockquote">
<h2 id="solution" class="anchored">Solution</h2>
<p>Answer: 2. α diversity of A = 4, α diversity of B = 3, β diversity between A and B = 5 The number of species in Lake A (the α diversity) is 4 and 1 of these is also found in Lake B; the number of species in Lake B is 3 and 1 of these is also in Lake A. The β diversity between A and C is calculated as (4 - 1) + (3 - 1) = 5. {: .solution} {: .challenge}</p>
</blockquote>
</blockquote>
</em></em></section><em><em>
</em></em></section><em><em>
<section id="how-do-we-calculate-diversity-from-metagenomic-samples" class="level2">
<h2 class="anchored" data-anchor-id="how-do-we-calculate-diversity-from-metagenomic-samples">How do we calculate diversity from metagenomic samples?</h2>
<p>We will calculate the diversity in our heathland sample <code>ERR4998593</code> and compare it with data from another site from the same study: <code>ERR4998600</code>. This is a fenland site (so lower and wetter than our heathland site).</p>
<p>There are 2 steps needed to calculate the diversity of our samples.</p>
<ol type="1">
<li>Create a Biological Observation Matrix, BIOM table, from the Kraken output. A BIOM table is a matrix of counts with samples in the columns and taxa in the rows. The values in the matrix are the counts of that taxa in that sample.</li>
<li>Analyse the BIOM table to generate diversity indices and relative abundance plots.</li>
</ol>
</section>
<section id="what-part-of-the-kraken-output-do-we-need" class="level2">
<h2 class="anchored" data-anchor-id="what-part-of-the-kraken-output-do-we-need">What part of the Kraken output do we need?</h2>
<p>We will use a command-line program called <a href="https://github.com/smdabdoub/kraken-biom"><code>kraken-biom</code></a> to convert our Kraken output into a BIOM table. <code>kraken-biom</code> takes the <code>.report</code> output of Kraken and creates a BIOM table in <a href="https://biom-format.org/"><code>.biom</code></a> format.</p>
<p>Move in to your <code>taxonomy</code> folder ~~~ cd ~/cs_course/analysis/taxonomy ~~~~ {: .bash}</p>
<p>List the files ~~~ ls -l ~~~~ {: .bash}</p>
<pre><code>-rw-rw-r-- 1 csuser csuser 3935007137 Apr  9 09:16 ERR4998593.kraken
-rw-rw-r-- 1 csuser csuser     424101 Apr  9 09:16 ERR4998593.report</code></pre>
<p>{: .output}</p>
<p>As we saw in the previous episode, <code>.kraken</code> and <code>.report</code> are the output files generated by Kraken.</p>
<p>We will also need the <code>ERR4998600</code> Kraken report. We have put this in our GitHub repo and it can be copied into your <code>taxonomy</code> directory on the instance using <code>wget</code>. This is a useful command for retrieving files from web servers and simply requires <code>wget</code> followed by the web address the file is stored at.</p>
<pre><code>wget https://cloud-span.github.io/nerc-metagenomics06-taxonomic-anno/files/ERR4998600.report</code></pre>
<p>{: .bash}</p>
<p>You should <code>ls</code> to check that this file has been downloaded.</p>
</section>
<section id="create-the-biom-table" class="level2">
<h2 class="anchored" data-anchor-id="create-the-biom-table">Create the BIOM table</h2>
<p><code>kraken-biom</code> has many options which you can see with the help command. However, we only need to specify an output format <code>--fmt</code> of <code>json</code> to use the file in the next step.</p>
<blockquote class="blockquote">
<h2 id="kraken-biom--h-output" class="anchored"><code>kraken-biom -h</code> output</h2>
<pre><code>usage: kraken-biom [-h] [--max {D,P,C,O,F,G,S}] [--min {D,P,C,O,F,G,S}] [-o OUTPUT_FP] [--otu_fp OTU_FP] [--fmt {hdf5,json,tsv}] [--gzip] [--version] [-v]
                   kraken_reports [kraken_reports ...]
                        Set the output format of the BIOM table. Default is HDF5.
Create BIOM-format tables (http://biom-format.org) from Kraken output  BIOM (v2.x) files are internally compressed by default, so this option is not needed when
(http://ccb.jhu.edu/software/kraken/).mt hdf5.
  --version             show program's version number and exit
The program takes as input, one or more files output from the kraken-report
tool. Each file is parsed and the counts for each OTU (operational taxonomic
unit) are recorded, along with database ID (e.g. NCBI), and lineage. The
extracted data are then stored in a BIOM table where each count is linked
to the Sample and OTU it belongs to. Sample IDs are extracted from the input
filenames (everything up to the '.').

OTUs are defined by the --max and --min arguments. By default these are
set to Order and Species respectively. This means that counts assigned
directly to an Order, Family, or Genus are recorded under the associated
OTU ID, and counts assigned at or below the Species level are assigned to
the OTU ID for the species. Setting a minimum rank below Species is not yet
available.

The BIOM format currently has two major versions. Version 1.0 uses the
JSON (JavaScript Object Notation) format as a base. Version 2.x uses the
HDF5 (Hierarchical Data Format v5) as a base. The output format can be
specified with the --fmt option. Note that a tab-separated (tsv) output
format is also available. The resulting file will not contain most of the
metadata, but can be opened by spreadsheet programs.

Version 2 of the BIOM format is used by default for output, but requires the
Python library 'h5py'. If the library is not installed, kraken-biom will
automatically switch to using version 1.0. Note that the output can
optionally be compressed with gzip (--gzip) for version 1.0 and TSV files.
Version 2 files are automatically compressed.

Usage examples
--------------
1. Basic usage with default parameters:

$ kraken-biom.py S1.txt S2.txt

  This produces a compressed BIOM 2.1 file: table.biom

2. BIOM v1.0 output:

$ kraken-biom.py S1.txt S2.txt --fmt json

  Produces a BIOM 1.0 file: table.biom

3. Compressed TSV output:

$ kraken-biom.py S1.txt S2.txt --fmt tsv --gzip -o table.tsv

  Produces a TSV file: table.tsv.gz

4. Change the max and min OTU levels to Class and Genus:

$ kraken-biom.py S1.txt S2.txt --max C --min G

Program arguments
-----------------

positional arguments:
  kraken_reports        Results files from the kraken-report tool.

optional arguments:
  -h, --help            show this help message and exit
  --max {D,P,C,O,F,G,S}
                        Assigned reads will be recorded only if they are at or below max rank. Default: O.
  --min {D,P,C,O,F,G,S}
                        Reads assigned at and below min rank will be recorded as being assigned to the min rank level. Default: S.
  -o OUTPUT_FP, --output_fp OUTPUT_FP
                        Path to the BIOM-format file. By default, the table will be in the HDF5 BIOM 2.x format. Users can output to a different format using the --fmt option. The output can also be gzipped using the --gzip option. Default path is: ./table.biom
  --otu_fp OTU_FP       Create a file containing just the (NCBI) OTU IDs for use with a service such as phyloT (http://phylot.biobyte.de/) to generate a phylogenetic tree for use in downstream analysis such as UniFrac, iTol (itol.embl.de), or PhyloToAST (phylotoast.org).
  --fmt {hdf5,json,tsv}      Set the output format of the BIOM table. Default is HDF5.
  --gzip                Compress the output BIOM table with gzip. HDF5 BIOM (v2.x) files are internally compressed by default, so this option is not needed when specifying --fmt hdf5.
  --version             show program's version number and exit
  -v, --verbose         Prints status messages during program execution.</code></pre>
<p>{: .output} {: .solution}</p>
</blockquote>
<p>With the next command, we are going to create a table in <a href="https://biom-format.org/">Biom</a> format from our two Kraken reports: <code>ERR4998593.report</code> and <code>ERR4998600.report</code>.</p>
<p>We customise the command with a couple of flags: - <code>--fmt json</code> tells kraken-biom that we want the output table to be in JSON format as opposed to the default HDF5 BIOM2.x format - <code>-o metagenome.biom</code> means our output table will be named <code>metagenome.biom</code></p>
<pre><code> kraken-biom ERR4998593.report ERR4998600.report --fmt json -o metagenome.biom</code></pre>
<p>{: .bash}</p>
<p><code>kraken-biom</code> uses both reports to generate the BIOM table. The BIOM table is in a file called <code>metagenome.biom</code>. ~~~ ls -l ~~~ {: .bash} ~~~ -rw-rw-r– 1 csuser csuser 3935007137 Apr 9 09:16 ERR4998593.kraken -rw-rw-r– 1 csuser csuser 424101 Apr 9 09:16 ERR4998593.report -rw-rw-r– 1 csuser csuser 404232 Apr 9 09:30 ERR4998600.report -rw-rw-r– 1 csuser csuser 741259 Apr 9 10:22 metagenome.biom ~~~ {: .output}</p>
</section>
<section id="analyse-the-biom-table-using-r" class="level2">
<h2 class="anchored" data-anchor-id="analyse-the-biom-table-using-r">Analyse the BIOM table using R</h2>
<p>We will be using an <code>R</code> package called <a href="https://joey711.github.io/phyloseq/"><code>phyloseq</code></a> to analyse our biom file. Other software for analyses of diversity include <a href="https://qiime2.org/">Qiime2</a>, <a href="https://www.wsi.uni-tuebingen.de/lehrstuehle/algorithms-in-bioinformatics/software/megan6/">MEGAN</a> and the <code>R</code> package <a href="https://vegandevs.github.io/vegan/"><code>Vegan</code></a></p>
<p>If you are very familiar with R and RStudio and already have them on your machine, you may want to install the packages needed and download the <code>metagenome.biom</code> file to do the analysis on your own computer. However, you do not need prior experience with R and RStudio for this part of the course: we have set up the analysis in RStudio Cloud, an online version of RStudio which has everything you need, including the code. We have given instructions for both options.</p>
<section id="option-a-i-know-r-and-rstudio." class="level3">
<h3 class="anchored" data-anchor-id="option-a-i-know-r-and-rstudio.">Option A: I know R and RStudio.</h3>
<p>If you know R and RStudio and already have them on your machine you may want to use this option.</p>
<ol type="1">
<li>Open RStudio<br>
</li>
<li>Install the packages<br>
You will need <code>phyloseq</code>, a Bioconductor package, and the <code>tidyverse</code> and <code>ggvenn</code> packages. Bioconductor packages are installed using the <code>install()</code> function from the <code>BioManager</code> package so we first install that, then <code>phyloseq</code>, <code>tidyverse</code> and <code>ggvenn</code>: ~~~ &gt; install.packages(“BiocManager”) &gt; BiocManager::install(“phyloseq”) &gt; install.packages(“tidyverse”) &gt; install.packages(“ggvenn”) ~~~ {: .language-r}</li>
<li>Make an RStudio project<br>
Make an RStudio project workshop by clicking on the drop-down menu on top right where it says Project: (None) and choosing New Project and then New Directory, then New Project. In the “Create project as a subdirectory” box, use Browse to navigate to the “cloudspan” folder. Name the RStudio Project ‘diversity’.</li>
<li>Download the <code>metagenome.biom</code> file to the project folder<br>
Download the file to the project folder using <code>scp</code>. Use a terminal that is <strong><em>not</em></strong> logged into the cloud instance and ensure you are in your <code>cloudspan</code> directory. Use <code>scp</code> to copy the file to the <code>diversity</code> folder - the command will look something like: ~~~ scp -i login-key-instanceNNN.pem csuser@instanceNNN.cloud-span.aws.york.ac.uk:~/cs_course/analysis/taxonomy/metagenome.biom diversity ~~~ {: .bash} Remember to replace NNN with the instance number specific to you.</li>
<li>Open a new script.</li>
</ol>
<p>Now go to <strong>Start the analysis</strong>.</p>
</section>
<section id="option-b-i-dont-know-r-and-rstudio." class="level3">
<h3 class="anchored" data-anchor-id="option-b-i-dont-know-r-and-rstudio.">Option B: I don’t know R and RStudio.</h3>
<p>If you don’t know R and RStudio we suggest you to use this option. We have installed the packages needed and put the data, <code>metagenome.biom</code> and a script <code>analysis.R</code> in the RStudio Cloud Project.</p>
<ol type="1">
<li>Make an RStudio Cloud account<br>
Go to <a href="https://rstudio.cloud/">https://rstudio.cloud/</a> and follow Get Started for Free. We recommend signing up with your Google account if you use one.<br>
</li>
<li>Follow the link to the <a href="https://posit.cloud/content/5663744">cloud-span-metagenomics</a> project.<br>
Open the project we have set up: <a href="https://posit.cloud/content/5663744">cloud-span-metagenomics</a>. You’ll get a message saying “Deploying project”. This will take a few seconds.<br>
</li>
<li>Open <code>analysis.R</code> from the Files pane on the bottom right of the display.</li>
</ol>
</section>
<section id="start-the-analysis" class="level3">
<h3 class="anchored">Start the Analysis</h3>
<p>If you are using RStudio Cloud, we will run through the code in <code>analysis.R</code> line by line. If you are using RStudio on your own machine you can type in the commands or copy them from <a href="../files/analysis.R">analysis.R</a></p>
<p>First load the packages we need. Put your cursor on the line you want to run and press <kbd>CTRL</kbd><kbd>ENTER</kbd><br>
~~~ library(“phyloseq”) library(“tidyverse”) library(“ggvenn”) ~~~ {: .language-r}</p>
<p>Now import the data in <code>metagenome.biom</code> into R using the <code>import_biom()</code> function from <code>phyloseq</code> ~~~ biom_metagenome &lt;- import_biom(“metagenome.biom”) ~~~ {: .language-r}</p>
<p>This command produces no output in the console but created a special class of R object which is defined by the <code>phyloseq</code> package and called it <code>biom_metagenome</code>. Click on the object name, biom_metagenome, in the Environment pane (top right), see the screenshot below. This will open a view of the object in the same pane as your script.</p>
<p>A phyloseq object is a special object in R. It has five parts, called ‘slots’ which you can see listed in the object view. These are <code>otu_table</code>, <code>tax_table</code>, <code>sam_data</code>, <code>phy_tree</code> and <code>refseq</code>. In our case, <code>sam_data</code>, <code>phy_tree</code> and <code>refseq</code> are empty. The useful data are in otu_table<code>and</code>tax_table`.</p>
<p><a href="{{ page.root }}/fig/r-phyloseq-obj.png"> <img src="{{ page.root }}/fig/r-phyloseq-obj.png" alt="Screenshot of RStudio showing the bio_metagenome object in the environment window which has been clicked on to open a view of the object. The five slots are listed in that view."> </a></p>
<p>Return to your script (click on the tab). Typing <code>biom_metagenome</code> will give some summary information about the <code>biom_metagenome</code> object:<br>
~~~ biom_metagenome ~~~ {: .language-r}</p>
<pre><code>phyloseq-class experiment-level object
otu_table()   OTU Table:         [ 7637 taxa and 2 samples ]
tax_table()   Taxonomy Table:    [ 7637 taxa by 7 taxonomic ranks ]</code></pre>
<p>{: .output}</p>
<p>The line starting <code>otu_table</code> tells us we have two samples - these are ERR4998593 and ERR4998600 - with a total of 7637 taxa. The <code>tax_table</code> again tells us how many taxa we have. The seven ranks indicates that we have some identifications down to species level. The taxonomic ranks are from the classification system of taxa from the most general (kingdom) to the most specific (species): kingdom/domain, phylum, class, order, family, genus, species.</p>
<p>We can view the <code>tax_table</code> with: ~~~ View(biom_metagenome@tax_table) ~~~ {: .language-r}</p>
<p>This table has the OTU identity in the row names and the samples in the columns. The values in the columns are the abundance of that OTU in that sample.</p>
<p><img src="{{ page.root }}/fig/03_02_phyloseq_taxtab.png" alt="A table where the taxonomic identification information of all OTUs is displayed. Each row represent one OTU and the columns its identification at different levels in the taxonomic taxonomic classification ranks, beginning with Kingdom until we reach Species in the seventh column "> <em> Figure 3. Table of the OTU data from our <code>biom_metagenome</code> object. <em></em></em></p><em><em>
<p>To make downstream analysis easier for us we will remove the prefix (e.g.&nbsp;<code>f__</code>) on each item. This contains information about the rank of the assigned taxonomy, we don’t want to lose this information so will and instead rename the header of each column of the DataFrame to contain this information.</p>
<p>To remove unnecessary characters we are going to use command <code>substring()</code>.</p>
<p>This command is useful to extract or replace characters in a vector. To use the command, we have to indicate the vector (x) followed by the first element to replace or extract (first) and the last element to be replaced (last). For instance: <code>substring (x, first, last)</code>. If a last position is not used it will be set to the end of the string.</p>
<p>The prefix for each item in <code>biom_metagenome</code> is made up of a letter and two underscores, for example: <code>o__Bacillales</code>. In this case “Bacillales” starts at position 4 with a B. So to remove the unnecessary characters we will use the following code:</p>
<pre><code>biom_metagenome@tax_table &lt;- substring(biom_metagenome@tax_table, 4)</code></pre>
<p>{: .language-r}</p>
<p>Let’s change the names of the columns too: ~~~<br>
colnames(biom_metagenome@tax_table) &lt;- c(“Kingdom”, “Phylum”, “Class”, “Order”, “Family”, “Genus”, “Species”) ~~~ {: .language-r}</p>
<p>Check it worked: ~~~<br>
View(biom_metagenome@tax_table) ~~~ {: .language-r}</p>
<p><img src="{{ page.root }}/fig/03_02_phyloseq_taxtab_e.png" alt="The same table we saw in Figure 3 but with informative headers in each of the columns. Now, we can see which of the columns are associated with which taxonomic classification rank"> <em> Figure 4. Table of the OTU data from our <code>biom_metagenome</code> object. With corrections. <em></em></em></p><em><em>
<p>How many OTUs are in each kingdom? We can find out by combining some commands. We need to: - turn the tax_table into a data frame (a useful data structure in R) - group by the Kingdom column - summarise by counting the number of rows for each Kingdom</p>
<p>This can be achieved with the following command: ~~~ biom_metagenome@tax_table %&gt;% data.frame() %&gt;% group_by(Kingdom) %&gt;% summarise(n = length(Kingdom)) ~~~ {: .language-r}</p>
<pre><code># A tibble: 4 × 2
  Kingdom       n
  &lt;chr&gt;     &lt;int&gt;
1 Archaea     339
2 Bacteria   7231
3 Eukaryota     1
4 Viruses      66</code></pre>
<p>{: .output} Most things are bacteria!</p>
<p>We can explore how many phlya we have and how many OTU there are in each phlya in a similar way. This time we will use View() to see the whole table because it won’t all print to the console - turn the tax_table into a data frame (a useful data structure in R) - group by the Phylum column - summarise by counting the number of rows for each phylum - viewing the result</p>
<p>This can be achieved with the following command: ~~~ biom_metagenome@tax_table %&gt;% data.frame() %&gt;% group_by(Phylum) %&gt;% summarise(n = length(Phylum)) %&gt;% View() ~~~ {: .language-r}</p>
<p>This shows us a table with a phylum, and the number times it appeared, in each row. The number of phyla is given by the number of rows in this table. By defualt, the table is sorted alphabetically by phylum. We can sort by frequency by clicking on the ‘n’ column. There are 3471 Proteobacteria and 1571 Actinobacteria for example.</p>
<p><img src="{{ page.root }}/fig/03_02_phyla_freq_table.png" alt="Two views of the phyla frequency table: sorted alphabetically by phylum on the left and by the number of OTUs (n) in each phylum on the right"></p>
<blockquote class="blockquote">
<h2 id="exercise-2-explore-the-orders" class="anchored" data-anchor-id="start-the-analysis">Exercise 2: Explore the Orders</h2>
<p>Adapt the code to explore how many Orders we have and how many OTU there are in each order.<br>
a) How many orders are there?<br>
b) What is the most common order?<br>
c) How many OTUs did not get down to order level?<br>
&gt; ## Solution &gt; You should the use the column name ‘Order’ instead of ‘Phylum’ in the code &gt; &gt; ~~~ &gt; biom_metagenome@tax_table %&gt;% &gt; data.frame() %&gt;% &gt; group_by(Order) %&gt;% &gt; summarise(n = length(Order)) %&gt;% &gt; View() &gt; ~~~ &gt; {: .language-r} &gt;<br>
&gt; a) 229. This is the number of rows in the table<br>
&gt; b) Hyphomicrobiales. Sorting the column n will bring this to the top. Hyphomicrobiales appears 480 times<br>
&gt; c) 66. If an OTU has not been identified to order level the order column will be blank. The table shows there were 66 such cases (you can find this more easily by sorting the column Order).<br>
&gt; {: .solution} {: .challenge}</p>
</blockquote>
</em></em></em></em></section><em><em><em>
</em></em></em></section><em><em><em>
<section id="plot-alpha-diversity" class="level2">
<h2 class="anchored" data-anchor-id="plot-alpha-diversity">Plot alpha diversity</h2>
<p>We want to explore the bacterial diversity of our samples, so we will remove all of the non-bacterial organisms. To do this we will generate a subset of all bacterial groups and save them. ~~~ bac_biom_metagenome &lt;- subset_taxa(biom_metagenome, Kingdom == “Bacteria”) ~~~ {: .language-r}</p>
<p>Now let’s look at some statistics of our bacterial metagenomes:</p>
<pre><code>bac_biom_metagenome</code></pre>
<p>{: .language-r} ~~~ phyloseq-class experiment-level object otu_table() OTU Table: [ 7231 taxa and 2 samples ] tax_table() Taxonomy Table: [ 7231 taxa by 7 taxonomic ranks ] ~~~ {: .output}</p>
<p><code>phyloseq</code> includes a function to find the sample names and one to count the number of reads in each sample.</p>
<p>Find the sample names with <code>sample_names()</code>:<br>
~~~ sample_names(bac_biom_metagenome) ~~~ {: .language-r} ~~~ “ERR4998593” “ERR4998600”<br>
~~~ {: .output}</p>
<p>Count the number of reads with <code>sample_sums()</code>:<br>
~~~ sample_sums(bac_biom_metagenome) ~~~ {: .language-r} ~~~ ERR4998593 ERR4998600 442490 305135 ~~~ {: .output}</p>
<p>The <code>summary()</code> function can give us an indication of species evenness<br>
~~~ summary(bac_biom_metagenome@otu_table) ~~~ {: .language-r} ~~~ ERR4998593 ERR4998600<br>
Min. : 0.00 Min. : 0.0<br>
1st Qu.: 1.00 1st Qu.: 2.0<br>
Median : 6.00 Median : 11.0<br>
Mean : 61.19 Mean : 42.2<br>
3rd Qu.: 31.50 3rd Qu.: 38.0<br>
Max. :60679.00 Max. :38768.0<br>
~~~ {: .output}</p>
<p>The median in sample ERR4998593 is 6, meaning many of OTU occur six times. The maximum is very high so at least one OTU is very abundant.</p>
<p>The <code>plot_richness()</code> command will give us a visual representation of the diversity inside the samples (i.e.&nbsp;α diversity): ~~~ plot_richness(physeq = biom_metagenome, measures = c(“Observed”,“Chao1”,“Shannon”)) ~~~ {: .language-r}</p>
<p><a href="{{ page.root }}/fig/03_02_plot_rich.png"> <img src="{{ page.root }}/fig/03_02_plot_rich.png" alt="A figure divided in three
  sections. Each of these sections represent a diferent alpha diversity index.
  Inside this sections, each point represent the value assigned on this index to
  the three different samples. We can see how the different indexes gives
  different values to the same sample."> </a> <em> Figure 5. Alpha diversity indexes for both samples. <em></em></em></p><em><em>
<p>Each of these metrics can give insight of the distribution of the OTUs inside our samples. For example Chao1 diversity index gives more weight to singletons and doubletons observed in our samples, while the Shannon is a measure of species richness and species evenness with more weigth on richness.</p>
<p>Use the following to open the manual page for plot_richness ~~~ ?plot_richness ~~~ {: .language-r}</p>
<blockquote class="blockquote">
<h2 id="exercise-3" class="anchored">Exercise 3:</h2>
<p>While using the help provided explore these options available for the function in <code>plot_richness()</code>: 1. <code>nrow</code> 2. <code>sortby</code> 3. <code>title</code></p>
<p>Use these options to generate new figures that show you other ways to present the data.</p>
<blockquote class="blockquote">
<h2 id="solution-1" class="anchored">Solution</h2>
<p>The code and the plot using the three options will look as follows: The “title” option adds a title to the figure. ~~~ plot_richness(physeq = biom_metagenome, title = “Alpha diversity indexes for both metagenomic samples”, measures = c(“Observed”,“Chao1”,“Shannon”)) ~~~ {: .language-r}</p>
<p><a href="{{ page.root }}/fig/03_02_plot_rich2.png"> <img src="{{ page.root }}/fig/03_02_plot_rich2.png" alt="Alpha diversity indexes for both samples with title"> </a></p>
<p>The “nrow” option arranges the graphics horizontally. ~~~ plot_richness(physeq = biom_metagenome, title = “Alpha diversity indexes for both metagenomic samples”, measures = c(“Observed”,“Chao1”,“Shannon”), nrow=3) ~~~ {: .language-r}</p>
<p><a href="{{ page.root }}/fig/03_02_plot_rich3.png"> <img src="{{ page.root }}/fig/03_02_plot_rich3.png" alt="Alpha diversity indexes for both samples horizontal with title"> </a></p>
<p>The “sortby” option orders the samples from least to greatest diversity depending on the parameter. In this case, it is ordered by “Shannon” and tells us that the ERR4998593 sample has the lowest diversity and the ERR4998600 sample the highest. ~~~ plot_richness(physeq = bac_biom_metagenome, title = “Alpha diversity indexes for both metagenomic samples”, measures = c(“Observed”,“Chao1”,“Shannon”), sortby = “Shannon”) ~~~ {: .language-r}</p>
<p><a href="{{ page.root }}/fig/03_02_plot_rich4.png"> <img src="{{ page.root }}/fig/03_02_plot_rich4.png" alt="Alpha diversity indexes for both samples with title sort by Shannon"> </a></p>
<p>{: .solution} {: .challenge}</p>
</blockquote>
</blockquote>
</em></em></section><em><em>
<section id="beta-diversity" class="level2">
<h2 class="anchored" data-anchor-id="beta-diversity">Beta diversity</h2>
<p>The β diversity between ERR4998593 and ERR4998600 can be calculated with the <code>distance()</code> function. For example, we can find the Bray–Curtis dissimilarity with: ~~~ distance(bac_biom_metagenome, method=“bray”) ~~~ {: .language-r} ~~~ ERR4998593 ERR4998600 0.5438328 ~~~ {: .output}</p>
<p>There are other methods of determining distance and we can view our options with: ~~~ distanceMethodList$vegdist ~~~ {: .language-r} ~~~ [1] “manhattan” “euclidean” “canberra” “bray” “kulczynski” “jaccard” “gower”<br>
[8] “altGower” “morisita” “horn” “mountford” “raup” “binomial” “chao”<br>
[15] “cao” ~~~ {: .output}</p>
<p>Any of these methods can be used in the same way used above, e.g. ~~~ distance(bac_biom_metagenome, method=“jaccard”) ~~~ {: .language-r} ~~~ ERR4998593 ERR4998600 0.7045229 ~~~ {: .output}</p>
<p>The output of this function is a distance matrix. When we have just two samples there is only one distance to calculate. If we had many samples, the output would have the pairwise distances between all of them</p>
</section>
<section id="reading" class="level2">
<h2 class="anchored" data-anchor-id="reading">Reading</h2>
<p>Tuomisto, H. A consistent terminology for quantifying species diversity? Yes, it does exist. Oecologia 164, 853–860 (2010). <a href="https://doi.org/10.1007/s00442-010-1812-0">https://doi.org/10.1007/s00442-010-1812-0</a></p>
<p>Whittaker, R. H. (1960) Vegetation of the Siskiyou Mountains, Oregon and California. Ecological Monographs, 30, 279–338</p>
<p>{% include links.md %}</p>



</section>

</em></em></em></em></em></em></em><a onclick="window.scrollTo(0, 0); return false;" role="button" id="quarto-back-to-top"><i class="bi bi-arrow-up"></i> Back to top</a></main><em><em><em> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp("https:\/\/Cloud-SPAN\.github\.io\/nercMtGn-bashAutomation\/");
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../../docs/lesson06-taxonomic-annotations/01-taxonomic.html" class="pagination-link" aria-label="Taxonomic Assignment">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text">Taxonomic Assignment</span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../../docs/lesson06-taxonomic-annotations/03-hands_on-diversity.html" class="pagination-link" aria-label="Taxonomic Analysis with R">
        <span class="nav-page-text">Taxonomic Analysis with R</span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</em></em></em></div><em><em><em> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>Licensed under <a href="https://creativecommons.org/licenses/by/4.0/">CC-BY 4.0</a> 2021–24 by <a href="https://cloud-span.york.ac.uk/">Cloud-SPAN</a></p>
</div>   
    <div class="nav-footer-center">
      <ul class="footer-items list-unstyled">
    <li class="nav-item">
    <a class="nav-link" href="../../about.qmd">
<p>About</p>
</a>
  </li>  
    <li class="nav-item">
    <a class="nav-link" href="../../docs/faq/index.qmd">
<p>FAQ</p>
</a>
  </li>  
    <li class="nav-item">
    <a class="nav-link" href="../../license.qmd">
<p>License</p>
</a>
  </li>  
    <li class="nav-item">
    <a class="nav-link" href="../../trademark.qmd">
<p>Trademark</p>
</a>
  </li>  
</ul>
    <div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/Cloud-SPAN/nercMtGn-bashAutomation/edit/main/docs/lesson06-taxonomic-annotations/02-Diversity-tackled-with-R.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li><li><a href="https://github.com/Cloud-SPAN/nercMtGn-bashAutomation/issues/new" class="toc-action"><i class="bi empty"></i>Report an issue</a></li></ul></div></div>
    <div class="nav-footer-right">
      <ul class="footer-items list-unstyled">
    <li class="nav-item compact">
    <a class="nav-link" href="https://twitter.com/quarto_pub">
      <i class="bi bi-twitter" role="img" aria-label="Quarto Twitter">
</i> 
    </a>
  </li>  
    <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/quarto-dev/quarto-cli">
      <i class="bi bi-github" role="img" aria-label="Quarto GitHub">
</i> 
    </a>
  </li>  
    <li class="nav-item compact">
    <a class="nav-link" href="https://quarto.org/docs/blog/index.xml">
      <i class="bi bi-rss" role="img" aria-label="Quarto Blog RSS">
</i> 
    </a>
  </li>  
</ul>
    </div>
  </div>
</footer>




</em></em></em></body></html>